spring.application.name=demo
#debug=true
logging.level.org.springframework.boot.context.properties=DEBUG
seat-routing.cookie=ticketcookie
seat-routing.local-node=java_gateway@gateway
seat-routing.node-res1=res1@res1
seat-routing.node-res2=res2@res2
seat-routing.node-res3=res3@res3
