spring.application.name=demo
#debug=true
logging.level.org.springframework.boot.context.properties=DEBUG
seat-routing.cookie=ticketcookie
seat-routing.local-node=java_gateway@gateway
seat-routing.node-res1=res1@res1
seat-routing.node-res2=res2@res2
seat-routing.node-res3=res3@res3

spring.kafka.bootstrap-servers=10.2.1.4:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
app.kafka.confirm-topic=reservation.confirmations
app.kafka.hold-expired-topic=hold.expired