services:
  res1:
    build: ../erlang
    container_name: res1
    hostname: res1
    environment:
      ERLANG_COOKIE: ticketcookie
      ERL_SNAME: res1
      MNESIA_DIR: /var/lib/mnesia
      MNESIA_NODES: res1@res1,res2@res2,res3@res3
      INIT_MNESIA: "true"
      DIST_MIN: "9100"
      DIST_MAX: "9105"
    volumes:
      - mnesia_res1:/var/lib/mnesia
    networks:
      - erlangnet
    ports:
      - "4369:4369"
      - "9100-9105:9100-9105"

  res2:
    build: ../erlang
    container_name: res2
    hostname: res2
    environment:
      ERLANG_COOKIE: ticketcookie
      ERL_SNAME: res2
      MNESIA_DIR: /var/lib/mnesia
      MNESIA_NODES: res1@res1,res2@res2,res3@res3
      INIT_MNESIA: "false"
      DIST_MIN: "9106"
      DIST_MAX: "9111"
    volumes:
      - mnesia_res2:/var/lib/mnesia
    networks:
      - erlangnet
    depends_on:
      - res1
    ports:
      - "4370:4369"
      - "9106-9111:9106-9111"

  res3:
    build: ../erlang
    container_name: res3
    hostname: res3
    environment:
      ERLANG_COOKIE: ticketcookie
      ERL_SNAME: res3
      MNESIA_DIR: /var/lib/mnesia
      MNESIA_NODES: res1@res1,res2@res2,res3@res3
      INIT_MNESIA: "false"
      DIST_MIN: "9112"
      DIST_MAX: "9117"
    volumes:
      - mnesia_res3:/var/lib/mnesia
    networks:
      - erlangnet
    depends_on:
      - res1
    ports:
      - "4371:4369"
      - "9112-9117:9112-9117"
      
  # gateway:
  #   build: ../java
  #   container_name: gateway
  #   hostname: gateway
  #   working_dir: /app
  #   volumes:
  #     - ../java/testJinterface:/app
  #   environment:
  #     ERLANG_COOKIE: ticketcookie
  #   command: ["bash", "-lc", "epmd -daemon && tail -f /dev/null"]
  #   networks:
  #     - erlangnet
  #   depends_on:
  #     - res1
  #     - res2
  #     - res3

  gateway:
    build: ../java/demo
    container_name: gateway
    hostname: gateway
    depends_on:
      - res1
      - res2
      - res3
      - kafka
    networks:
      - erlangnet
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      ERLANG_COOKIE: ticketcookie
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    hostname: zookeeper
    networks:
      - erlangnet
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    networks:
      - erlangnet
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  chat-consumer:
    build: ./chat-consumer-java
    container_name: chat-consumer
    depends_on:
      - kafka
    networks:
      - erlangnet
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_CONFIRM_TOPIC: reservation.confirmations
      KAFKA_EXPIRED_TOPIC: hold.expired
      GOOGLE_CHAT_WEBHOOK_URL: https://chat.googleapis.com/v1/spaces/AAQAj1AwqAo/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=zezIgKfIu5wz1Ww5rEQdzFc2tRskQPylucG5dy3jNI8

  worker:
    build: ../java/worker
    container_name: worker
    hostname: worker
    depends_on:
      - kafka
    networks:
      - erlangnet
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    restart: on-failure

volumes:
  mnesia_res1:
  mnesia_res2:
  mnesia_res3:

networks:
  erlangnet:
    driver: bridge
